apiVersion: v2
name: vault
version: 0.8.2

appVersion: 1.8.4

description: Official HashiCorp Vault Chart

keywords: 
 - vault
 - security
 - encryption
 - secrets
 - management
 - automation
 - infrastructure

sources:
  - https://github.com/hashicorp/vault
  - https://github.com/hashicorp/vault-helm
  - https://github.com/hashicorp/vault-k8s
  - https://github.com/hashicorp/vault-csi-provider

description: stakater chart for vault , forked from hashicorp/vault-helm
